# Generated by Django 2.2 on 2020-03-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20200302_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(related_name='post', to='category.Category'),
        ),
        migrations.AlterModelTable(
            name='post',
            table=None,
        ),
    ]
