# Generated by Django 2.2 on 2020-02-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='name')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='time')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='time')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'daste bandi1',
            },
        ),
    ]
