# Generated by Django 2.2 on 2020-02-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20200229_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Tarikh'),
        ),
    ]
