# Generated by Django 2.2 on 2020-03-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20200229_1252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Commentes'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterModelTable(
            name='comment',
            table=None,
        ),
    ]
