# Generated by Django 2.2 on 2020-03-02 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_auto_20200301_1151'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='author',
            table='author',
        ),
    ]
