# Generated by Django 2.2 on 2020-03-02 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0004_auto_20200302_1357'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='author',
            table=None,
        ),
    ]
